import { registerSW } from 'virtual:pwa-register'

// Register the PWA service worker generated by vite-plugin-pwa
const updateSW = registerSW({
  immediate: true,
  onNeedRefresh() {
    // Optionally prompt user to refresh
    // e.g., show a toast/button to call updateSW(true)
  },
  onOfflineReady() {
    // App is ready to work offline
  },
})

